
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDleftPLUSMINUSleftTIMESDIVIDErightNOTUMINUSAND BOOLEAN DIVIDE LPAREN MINUS NOT NUMBER OR PLUS RPAREN TIMES\n    expr : expr PLUS expr\n         | expr MINUS expr\n         | expr TIMES expr\n         | expr DIVIDE expr\n         | expr AND expr\n         | expr OR expr\n         | NOT expr\n         | MINUS expr %prec UMINUS\n         | LPAREN expr RPAREN\n         | NUMBER\n         | BOOLEAN\n    '
    
_lr_action_items = {'NOT':([0,2,3,4,7,8,9,10,11,12,],[3,3,3,3,3,3,3,3,3,3,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[2,8,2,2,2,-10,-11,2,2,2,2,2,2,-8,-7,8,-1,-2,-3,-4,8,8,-9,]),'LPAREN':([0,2,3,4,7,8,9,10,11,12,],[4,4,4,4,4,4,4,4,4,4,]),'NUMBER':([0,2,3,4,7,8,9,10,11,12,],[5,5,5,5,5,5,5,5,5,5,]),'BOOLEAN':([0,2,3,4,7,8,9,10,11,12,],[6,6,6,6,6,6,6,6,6,6,]),'$end':([1,5,6,13,14,16,17,18,19,20,21,22,],[0,-10,-11,-8,-7,-1,-2,-3,-4,-5,-6,-9,]),'PLUS':([1,5,6,13,14,15,16,17,18,19,20,21,22,],[7,-10,-11,-8,-7,7,-1,-2,-3,-4,7,7,-9,]),'TIMES':([1,5,6,13,14,15,16,17,18,19,20,21,22,],[9,-10,-11,-8,-7,9,9,9,-3,-4,9,9,-9,]),'DIVIDE':([1,5,6,13,14,15,16,17,18,19,20,21,22,],[10,-10,-11,-8,-7,10,10,10,-3,-4,10,10,-9,]),'AND':([1,5,6,13,14,15,16,17,18,19,20,21,22,],[11,-10,-11,-8,-7,11,-1,-2,-3,-4,-5,11,-9,]),'OR':([1,5,6,13,14,15,16,17,18,19,20,21,22,],[12,-10,-11,-8,-7,12,-1,-2,-3,-4,-5,-6,-9,]),'RPAREN':([5,6,13,14,15,16,17,18,19,20,21,22,],[-10,-11,-8,-7,22,-1,-2,-3,-4,-5,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,3,4,7,8,9,10,11,12,],[1,13,14,15,16,17,18,19,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_expr','combinado.py',36),
  ('expr -> expr MINUS expr','expr',3,'p_expr','combinado.py',37),
  ('expr -> expr TIMES expr','expr',3,'p_expr','combinado.py',38),
  ('expr -> expr DIVIDE expr','expr',3,'p_expr','combinado.py',39),
  ('expr -> expr AND expr','expr',3,'p_expr','combinado.py',40),
  ('expr -> expr OR expr','expr',3,'p_expr','combinado.py',41),
  ('expr -> NOT expr','expr',2,'p_expr','combinado.py',42),
  ('expr -> MINUS expr','expr',2,'p_expr','combinado.py',43),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr','combinado.py',44),
  ('expr -> NUMBER','expr',1,'p_expr','combinado.py',45),
  ('expr -> BOOLEAN','expr',1,'p_expr','combinado.py',46),
]
